### ISSUE TITLE
Problems plotting band structure with HSE06

### ISSUE THREAD

**Issue by TheGreatDeadOne** [romerogroup/pyprocar#146]
Pyprocar can even plot graphs properly, but the software can't identify the symmetry points for the kpath labels. I tried using KPOINTS from an SCF, but the package only managed to list the labels but not the band structure.

![Figure_1](https://github.com/romerogroup/pyprocar/assets/64573015/dc0c2ac3-223d-42c6-8a05-3deb6a511026)
![Figure_2](https://github.com/romerogroup/pyprocar/assets/64573015/9380bcd6-acc4-49b3-ba2a-64f1c352dfe8)

**Comment by lllangWV** [comment]
Hello,

Can I see your input files? Also, what files are in your directory?

Logan Lang

**Comment by TheGreatDeadOne** [comment]
> Hello,
> 
> Can I see your input files? Also, what files are in your directory, and what code are you using?
> 
> Logan Lang

I'm using VASP. The calculation files are attached.
[hse.zip](https://github.com/romerogroup/pyprocar/files/15227419/hse.zip)

**Comment by lllangWV** [comment]
Thanks for the files!

Upon reviewing your files, the issue seems to stem from the explicit k-points path specified in the KPOINTS file. We currently, do not have a method to parse this.

I can incorporate this functionality, but it will take a few days to implement.

In the meantime, I recommend using line mode to generate the k-path, as indicated in your KPATH file. However, please note a discrepancy: the KPATH file seems to suggest 180 k-points for the kpath, while the PROCAR file contains 190. Therefore, simply replacing the KPOINTS file with the path from the KPATH file won’t work. You'll need to rerun the calculation to resolve this.

Try this and let me know if you run into any issues again!

Logan Lang

**Comment by TheGreatDeadOne** [comment]
> Thanks for the files!
> 
> Upon reviewing your files, the issue seems to stem from the explicit k-points path specified in the KPOINTS file. We currently, do not have a method to parse this.

 Okay, got it
 
> Try this and let me know if you run into any issues again!

Thanks for the tips, I'll give it a try. 

> Logan Lang
